### ISSUE TITLE
feline is gone when cursor is at a matching bracket

### ISSUE THREAD

**Issue by kohane27** [Hitesh-Aggarwal/feline_theme.nvim#1]
Hello there. Hope you're doing well. Thank you for creating this config for `feline`. I have a question however. Please see the images below.

Normal expected behavior: `feline` is shown at all times:

![2023-01-04-17-31-32](https://user-images.githubusercontent.com/57322459/210525414-e2253c4a-d490-496d-9942-88f470389c5c.png)

Unexpected behavior: Whenever `feline` is at a matching bracket:

![2023-01-04-17-31-36](https://user-images.githubusercontent.com/57322459/210525439-c6ffde3c-adf1-4c88-8c7e-e98e84e24119.png)

I couldn't figure out why the whole bar is gone. I've tested against the default `feline.setup({})` and this behavior doesn't happen with the default setup.

```lua
local status_ok, feline = pcall(require, "feline")
if not status_ok then
  print("feline not working")
end

local tokyonight = {
  fg = "#c8d3f5",
  bg = "#1e2030",
  bg_dark = "#222436",
  green = "#c3e88d",
  yellow = "#ffc777",
  purple = "#fca7ea",
  orange = "#d19a66",
  fg_dark = "#a9b1d6",
  red = "#ff757f",
  blue = "#82aaff",
  dark_red = "#c53b53",
}

local provide = function(provider, fg_color, bg_color, style, left_sep, right_sep, enabled)
  provider = provider or " "
  fg_color = fg_color or "fg"
  bg_color = bg_color or "bg"
  style = style or "NONE"
  left_sep = left_sep or ""
  right_sep = right_sep or ""
  enabled = enabled or true
  return {
    provider = provider,
    hl = {
      fg = fg_color,
      bg = bg_color,
      style = style,
    },
    left_sep = left_sep,
    right_sep = right_sep,
    enabled = enabled,
  }
end

local left = {
  provide(" ", "blue", "blue"),
  provide("git_branch", "purple", "bg", "bold", "block", "block"),
  provide(
    { name = "file_type", opts = { filetype_icon = true, case = "titlecase" } },
    "fg",
    "bg",
    "NONE",
    "block",
    "block"
  ),
  provide(" "),
  provide("git_diff_added", "green"),
  provide("git_diff_removed", "red"),
  provide("git_diff_changed", "fg"),
  provide(" ", "fg", "bg", "NONE", "block", "block"),
  provide("diagnostic_errors", "dark_red"),
  provide("diagnostic_warnings", "yellow"),
  provide("diagnostic_hints", "blue"),
  provide("diagnostic_info"),
}

local right = {
  provide("lsp_client_names", "fg_dark", "bg", "NONE", "block", "block"),
  provide("position", "green", "bg", "NONE", "block", "block"),
  provide("line_percentage", "orange", "bg", "NONE", "block", "block"),
  provide(" ", "blue", "blue"),
}

local left_inactive = {
  provide(" ", "blue", "blue"),
  provide(
    { name = "file_type", opts = { filetype_icon = true, case = "titlecase" } },
    "fg",
    "bg",
    "NONE",
    "block",
    "block"
  ),
}

local right_inactive = {
  provide("position", "green", "bg", "NONE", "block", "block"),
  provide("line_percentage", "orange", "bg", "NONE", "block", "block"),
  provide(" ", "blue", "blue"),
}

local components = {
  active = {
    left,
    right,
  },
  inactive = {
    left_inactive,
    right_inactive,
  },
}

feline.setup({
  components = components,
  theme = tokyonight,
})

```

Any help is much appreciated. Thank you!

**Comment by Hitesh-Aggarwal** [comment]
Thanks for raising the issue. I am currently unable to work (out of town) and will be able to look at the situation after 2-3 weeks. What you can try for now is copy the code in your own config instead of using the plugin directly. Then you can try hacking on your own. Thanks..

**Comment by kohane27** [comment]
Hello @Hitesh-Aggarwal ! Thank you for your quick reply and apologies for not looking into this issue of mine hard enough. I figured it out. It's the plugin [vim-matchup](https://github.com/andymass/vim-matchup#faq) causing this issue. From [FAQ](https://github.com/andymass/vim-matchup#faq):

> Why is there a weird entry on the status line?
> 
> This is a feature which helps you see matches that are outside of the vim screen, similar to some IDEs. If you wish to disable it, use `let g:matchup_matchparen_offscreen = {}`

After setting the following:

```lua
vim.cmd([[
let g:matchup_matchparen_offscreen = {}
]])
```

I no longer have this issue. Not sure why I don't have this issue when using the default feline config. Anyway, thank you again:)
